# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidiarycompany',
            old_name='main_company',
            new_name='owner',
        ),
    ]
