# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_total_eae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='eae',
            new_name='company_estimated_earnings',
        ),
    ]
