# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20170723_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_estimated_earnings',
            new_name='eae',
        ),
    ]
