# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20170720_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiarycompany',
            name='main_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.MainCompany'),
        ),
    ]
