# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20170723_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='eae',
            new_name='earnings',
        ),
    ]
