# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20170720_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidiarycompany',
            name='main_company',
        ),
    ]
