# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_subsidiarycompany_main_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eae', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='MainCompany',
        ),
        migrations.DeleteModel(
            name='SubsidiaryCompany',
        ),
    ]
