# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20170721_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=b'', unique=True),
        ),
    ]
