# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20170721_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='eae',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=b'', max_length=40, unique=True),
        ),
    ]
