# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20170721_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
